[tool.bumpversion]
allow_dirty = false
commit = true
commit_args = ""
current_version = "2.0.1"
message = "Bump version: {current_version} → {new_version}"
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)"
replace = "{new_version}"
sign_tags = false
serialize = ["{major}.{minor}.{patch}"]
search = "{current_version}"
tag = false
tag_name = "v{new_version}"
tag_message = "Bump version: {current_version} → {new_version}"
