name: Make tagged release

on:
  pull_request:
    types:
      - closed

jobs:
  tag_release:
    runs-on: ubuntu-latest

    steps:
    - name: 📃 Check out code
      uses: actions/checkout@v4

    - name: 🐍 Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: 🏷️ Create Release Tag
      if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.base.ref == 'master'
      run: |
        VERSION=$(sed -n 's/current_version = "\([^"]*\)"/\1/p' pyproject.toml)
        echo "Creating tag ${VERSION}.."

        # Check if tag already exists
        git tag -l | grep "${VERSION}" && echo "❌ Tag ${VERSION} already exists" && exit 1

        # Create tag
        git tag "${VERSION}" "${GITHUB_SHA}"
        git push origin "${VERSION}"
